
server:
  port: 5555

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Inclui uma rota no Spring Boot Actuator chamada de routes que lista
# as rotas que ele encontrou no eureka, que são os micro serviços.
management:  endpoints:    web:      exposure:        include:        - "routes"