
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: 'city'
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/city?useSSL=false
    username: postgres
    password: postgres
    
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    